repository: AussieGuy0/AussieGuy0.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
highlighter: rouge
permalink: pretty
exclude:
  - CNAME
  - Makefile
  - vendor
collections:
  read_books:
    output: true
  tils:
    output: true

# SEO
title: Anthony Bruno
description: "Anthony Bruno - Software Engineer"
url: https://anthonybruno.dev
logo: "/favicon.ico"
author:
  name: Anthony Bruno
  twitter: DownUnder_Dev
  url: https://anthonybruno.dev
twitter:
  username: DownUnder_Dev
  card: summary
social:
  name: Anthony Bruno
  links:
    - https://twitter.com/DownUnder_Dev
    - https://github.com/AussieGuy0
    - https://dev.to/aussieguy
    - https://au.linkedin.com/in/anthonybruno1996
